---
title: "Tarea # 3"
author: "Fernando Bermúdez-Kuminev"
date: "2020-11-07"
output:
  html_document:
    theme: readable    
    toc: true
    toc_depth: 3
    toc_float:
      collapsed: false
      smooth_scroll: false    
---

```{r setup, include=FALSE}
library(knitr)

knitr::opts_chunk$set(echo = TRUE)
```

```{r eval = FALSE, message = FALSE, include=FALSE}

install.packages("leaflet")

install.packages("tidyr")
```

```{r message = FALSE, include=FALSE}

library(leaflet)

library(sf)

library(tidyr)

library(dplyr)
```

# POSITIVOS

```{r message=FALSE, warning=FALSE, include=FALSE}
#Positivos
sf_cantones <-
  st_read(
    "https://raw.githubusercontent.com/taller-r-jornadas-sigtd-2020/datos/master/cantones.geojson", 
    quiet = T
  )

casos_positivos <- 
  read.csv("https://raw.githubusercontent.com/pf0953-programaciongeoespacialr-2020/datos/master/covid19/ms/06_27_CSV_POSITIVOS.csv")

df_positivos<-
  casos_positivos %>%
  pivot_longer(
    cols = c(-cod_provin, -provincia, -cod_canton, -canton), 
    names_to = "fecha", 
    values_to = "positivos"
  )

df_positivos$fecha <- as.Date(df_positivos$fecha, "X%d.%m.%Y")

df_positivos_uf <- 
df_positivos %>%
filter(fecha == max(fecha), na.rm = TRUE) %>%
dplyr::select(cod_canton, positivos)

sf_positivos_cantones_uf<-
  left_join(sf_cantones, df_positivos_uf, by = c('cod_canton')) %>%
  arrange(desc(positivos))

bins <- c(0, 100, 500, 1000, 2000, Inf)
paleta <- colorBin("YlOrRd", domain = sf_positivos_cantones_uf$activos, bins = bins)


Mapa_1 <- leaflet(sf_positivos_cantones_uf)%>% 
  fitBounds(lng1 = -86, lng2 = -82, lat1 = 8, lat2 = 11)%>% 
  addTiles() %>% 
  addProviderTiles(providers$Thunderforest.OpenCycleMap, group = "Rutas") %>%
  addProviderTiles(providers$OpenTopoMap, group = "Topografia") %>%
  addProviderTiles(providers$Esri.WorldImagery, group = "Imagen satelital")  %>% 
  addPolygons(fillColor = ~paleta(positivos), stroke=T, fillOpacity = 0.7,
              color="black", weight=0.2, opacity= 0.5, group = "Positivos", popup = paste(
    "Cantón: ", sf_positivos_cantones_uf$canton, "<br>",
    "Positivos: ", sf_positivos_cantones_uf$positivos)
    ) %>% 
  addLegend("bottomright", pal = paleta, values = ~positivos, title = "Casos positivos", opacity = 1, group = "Positivos"
  ) %>%
  addLayersControl(
    baseGroups = c("Rutas", "Topografia", "Imagen satelital"),
    overlayGroups = c("Positivos"),
    options = layersControlOptions(collapsed = TRUE)) %>%
   addMiniMap(
    toggleDisplay = TRUE,
    position = "bottomleft",
    tiles = providers$OpenTopoMap
  )

```
```{r}
Mapa_1

```

# ACTIVOS

```{r echo=TRUE, include=FALSE}

casos_activos <- 
  read.csv("https://raw.githubusercontent.com/pf0953-programaciongeoespacialr-2020/datos/master/covid19/ms/06_27_CSV_ACTIVOS.csv")

df_activos<-
  casos_activos %>%
  pivot_longer(
    cols = c(-cod_provin, -provincia, -cod_canton, -canton), 
    names_to = "fecha", 
    values_to = "activos"
  )

df_activos$fecha <- as.Date(df_activos$fecha, "X%d.%m.%Y")

df_activos_uf <- 
df_activos %>%
filter(fecha == max(fecha), na.rm = TRUE) %>%
dplyr::select (cod_canton, activos)

View(df_activos_uf)

sf_activos_cantones_uf<-
  left_join(sf_cantones, df_activos_uf, by = c('cod_canton')) %>%
  arrange(desc(activos))

bins <- c(0, 50, 100, 150, 2000)
paleta2 <- colorBin("Greens", domain = sf_activos_cantones_uf$activos, bins = bins)


Mapa_2 <- leaflet(sf_activos_cantones_uf)%>% 
  fitBounds(lng1 = -86, lng2 = -82, lat1 = 8, lat2 = 11)%>% 
  addTiles() %>% 
  addProviderTiles(providers$Thunderforest.OpenCycleMap, group = "Rutas") %>%
  addProviderTiles(providers$OpenTopoMap, group = "Topografia") %>%
  addProviderTiles(providers$Esri.WorldImagery, group = "Imagen satelital")  %>% 
  addPolygons(fillColor = ~paleta2(activos), stroke=T, fillOpacity = 0.7,
              color="black", weight=0.2, opacity= 0.5, group = "Activos", popup = paste(
    "Cantón: ", sf_activos_cantones_uf$canton, "<br>",
    "Activos: ", sf_activos_cantones_uf$activos)
    ) %>% 
  addLegend("bottomright", pal = paleta2, values = ~activos, title = "Casos activos", opacity = 1, group = "Activos"
  ) %>%
  addLayersControl(
    baseGroups = c("Rutas", "Topografia", "Imagen satelital"),
    overlayGroups = c("Activos"),
    options = layersControlOptions(collapsed = TRUE))%>%
   addMiniMap(
    toggleDisplay = TRUE,
    position = "bottomleft",
    tiles = providers$OpenTopoMap
  )   

```

```{r}
Mapa_2

```

# RECUPERADOS


```{r echo=TRUE, include=FALSE}
#Recuperados

casos_recupe <- 
  read.csv("https://raw.githubusercontent.com/pf0953-programaciongeoespacialr-2020/datos/master/covid19/ms/06_27_CSV_RECUP.csv")

df_recupe<-
  casos_recupe %>%
  pivot_longer(
    cols = c(-cod_provin, -provincia, -cod_canton, -canton), 
    names_to = "fecha", 
    values_to = "recupe"
  )

df_recupe$fecha <- as.Date(df_recupe$fecha, "X%d.%m.%Y")

df_recupe_uf <- 
df_recupe %>%
filter(fecha == max(fecha), na.rm = TRUE) %>%
dplyr::select (cod_canton, recupe)

sf_recupe_cantones_uf<-
  left_join(sf_cantones, df_recupe_uf, by = c('cod_canton')) %>%
  arrange(desc(recupe))

```

# FALLECIDOS


```{r echo=TRUE, include=FALSE}
#Fallecidos

casos_fallecidos <- 
  read.csv("https://raw.githubusercontent.com/pf0953-programaciongeoespacialr-2020/datos/master/covid19/ms/06_27_CSV_FALLECIDOS.csv")

df_fallecidos<-
  casos_fallecidos %>%
  pivot_longer(
    cols = c(-cod_provin, -provincia, -cod_canton, -canton), 
    names_to = "fecha", 
    values_to = "fallecidos"
  )

df_fallecidos$fecha <- as.Date(df_fallecidos$fecha, "X%d.%m.%Y")

df_fallecidos_uf <- 
df_fallecidos %>%
filter(fecha == max(fecha), na.rm = TRUE) %>%
dplyr::select (cod_canton, fallecidos)

sf_fallecidos_cantones_uf<-
  left_join(sf_cantones, df_fallecidos_uf, by = c('cod_canton')) %>%
  arrange(desc(fallecidos))

```

# Elementos

```{r echo=TRUE, include=FALSE}
sf_cantones_total <-
    left_join(sf_cantones, df_positivos_uf, by = c('cod_canton')) %>%
    left_join (df_fallecidos_uf) %>%
    left_join (df_recupe_uf) %>%
    left_join (df_activos_uf)

View(sf_cantones_total)

bins <- c(0, 50, 100, 200, 400)

paleta1 <- colorBin("YlOrRd", domain = sf_cantones_total$positivos, bins = bins)

paleta2 <- colorBin("Greens", domain = sf_cantones_total$activos, bins = bins)

paleta3 <- colorBin("Blues", domain = sf_cantones_total$recupe, bins = bins)

paleta4 <- colorBin("Reds", domain = sf_cantones_total$fallecidos, bins = bins)

```

# MAPA GENERAL

```{r echo=TRUE}
leaflet(sf_cantones_total) %>% 
  fitBounds(lng1 = -86, lng2 = -82, lat1 = 8, lat2 = 11) %>% 
  addTiles() %>% 
  addProviderTiles(providers$Thunderforest.OpenCycleMap, group = "Rutas") %>%
  addProviderTiles(providers$OpenTopoMap, group = "Topografia") %>%
  addProviderTiles(providers$Esri.WorldImagery, group = "Imagen satelital")  %>% 
  addPolygons(fillColor = ~paleta1(positivos), stroke=T, fillOpacity = 0.7,
              color= "black", weight=0.2, opacity= 0.5, group = "Positivos", popup = paste(
    "Cantón:", sf_cantones_total$canton, "<br>",
    "Positivos:", sf_cantones_total$positivos)
    ) %>% 
  addLegend("bottomright", pal = paleta1, values = ~positivos, title = "Casos positivos", opacity = 1, group = "Positivos"
  ) %>% 
  addPolygons(fillColor = ~paleta2(activos), stroke=T, fillOpacity = 0.7,
              color= "black", weight=0.2, opacity= 0.5, group = "Activos", popup = paste(
    "Cantón:", sf_cantones_total$canton, "<br>",
    "Activos:", sf_cantones_total$activos)
    ) %>% 
  addLegend("bottomright", pal = paleta2, values = ~activos, title = "Casos activos", opacity = 1, group = "Activos"
  ) %>%
  addPolygons(fillColor = ~paleta3(recupe), stroke=T, fillOpacity = 0.7,
              color= "black", weight=0.2, opacity= 0.5, group = "Recuperados", popup = paste(
    "Cantón:", sf_cantones_total$canton, "<br>",
    "Recuperados", sf_cantones_total$recupe)
    ) %>% 
  addLegend("bottomleft", pal = paleta3, values = ~recupe, title = "Casos recuperados", opacity = 1, group = "Recuperados"
  ) %>% 
  addPolygons(fillColor = ~paleta4(fallecidos), stroke=T, fillOpacity = 0.7,
              color= "black", weight=0.2, opacity= 0.5, group = "Fallecidos", popup = paste(
    "Cantón:", sf_cantones_total$canton, "<br>",
    "Fallecidos", sf_cantones_total$fallecidos)
    ) %>% 
  addLegend("bottomleft", pal = paleta4, values = ~recupe, title = "Casos fallecidos", opacity = 1, group = "Fallecidos"
  ) %>%
   addLayersControl(
    baseGroups = c("Rutas", "Topografia", "Imagen satelital"),
    overlayGroups = c("Positivos", "Activos", "Recuperados", "Fallecidos"),
    options = layersControlOptions(collapsed = TRUE)
    ) %>%
   addMiniMap(
    toggleDisplay = TRUE,
    position = "topleft",
    tiles = providers$OpenTopoMap
  )
```
